#+hugo_base_dir: ../
#+hugo_section: posts
#+options: author:nil
* A New Notebook
  :PROPERTIES:
  :EXPORT_FILE_NAME: title-post.md
  :EXPORT_DATE: <2019-07-12 Fri>
  :END:
  If you are like me you probably own more nice looking notebooks than
  you have finished writing in. Buying a notebook is mostly like
  buying a difficult but impressive book to read. When you buy it you
  are buying what it promises to be for you. It promises to make you
  well read, or in the case of the notebook, it promises that you will
  have ideas worth writing down.

  Starting a blog is like this. 
  
  This blog is part of a naive attempt to be more public with my ideas
  and to work harder at drawing myself out into the wider world. This
  is not my inclination so it will be difficult. The choice of the
  title comes from Kierkegaard's /Sickness Unto Death,/ and I find it
  fitting for myself today. 

  The despair of possibility is the crippling feeling you get in front
  of a blank page. Or more broadly it is the feeling you get in the
  face of the blank rest of your life. There are a number of ways to
  try to resolve this despair. (I might be wrong about applying this
  category here.) We can devote ourselves to our own fulfillment or an
  ethical ideal. We can even devote ourselves to a religion in an act
  of faith. Kierkegaard spends a lot of time on these different
  categories, and it is easy to get caught up in trying to think of
  them as simply a system.

  That's fine in many cases, but today I am interested in looking at how
  each of Kierkegaard's ways of resolving the despair of possibility
  can be understood as not only responses to the life project, but
  also as responses to individual projects and tasks in our lives. How
  do the various responses to despair interact with the terror of the
  blank page?
  
  What would it mean to take these categories into particular bits of
  life? In many of our areas of life we face things like the despair
  of possibility. I suppose the way forward is to choose one of
  Kierkegaard's three options. We can choose to please ourselves with
  our work. And that provides some guidance. We can choose to try to
  make our work good in itself and for others. That maybe provides
  more guidance. Or we can do it for God. What this means I do not
  really know. It has to somehow include the other options, but what
  this means is tricky. I need more time to find out what this means.
  Maybe it involves doing things for others and for yourself, but all
  somehow as an offering. Both you and others perfectly served but
  neither for themselves all somehow pointing beyond. Also,
  Kierkegaard had this idea of faith being the holding of the infinite
  within the finite. There is somehow a realization of meaning within
  existence. Maybe that is part of it as well.


* Typical Experiences
  :PROPERTIES:
  :EXPORT_FILE_NAME: typical-experiences.md
  :EXPORT_DATE: <2019-07-16 Tue>
  :END:
   We have certain experiences that we see as typical to us. This is
   interesting. We can tell a lot about what we think of ourselves and
   our identities by what experiences we call typical. What is
   interesting about them is that the list of things that we do that
   we see as typical does not necessarily match up with what we
   actually do all the time. You see this kind of behavior in people
   who are particularly hard on themselves. Failure is typical and
   success is a freak accident. This is amusingly still believed even
   when in that person's life the number of successes way over
   balances the number of failures. 

   Typical experiences flow out of who we think we are. They are
   expressions and manifestations of our identity. They allow us to
   have an existence within the constant ebb and flow of our
   experiences. They keep us from seeing things like our digestion and
   sweating as core to who we are. I would not want to live without
   this function of my identity, but it can often deceive us. Our
   subjective experience of ourselves can become strongly skewed and
   this likely by the same mechanism that helps us filter the signal
   from the noise in our day to day experience. Somehow we can get
   confused about what is the signal in our experiences and what is
   the noise. This confusion comes from a core interpretive mistake
   about who we are. 

   I know of no quick fix for this, but it is a call to look at other
   voices in determining who we are and especially the meaning of
   events in our lives. We too often jump to conclusions based on a
   clear idea of who we think we are. Maybe a good way forward is to
   think about the experiences themselves as if they were a part of
   another person we did not know. What would we assume about this
   person's identity and how would that contrast with ours. 

   
