#+hugo_base_dir: ../
#+hugo_section: posts
#+options: author:nil
* A New Notebook
  :PROPERTIES:
  :EXPORT_FILE_NAME: title-post.md
  :EXPORT_DATE: <2019-07-12 Fri>
  :END:
  If you are like me you probably own more nice looking notebooks than
  you have finished writing in. Buying a notebook is mostly like
  buying a difficult but impressive book to read. When you buy it you
  are buying what it promises to be for you. It promises to make you
  well read, or in the case of the notebook, it promises that you will
  have ideas worth writing down.

  Starting a blog is like this. 
  
  This blog is part of a naive attempt to be more public with my ideas
  and to work harder at drawing myself out into the wider world. This
  is not my inclination so it will be difficult. The choice of the
  title comes from Kierkegaard's /Sickness Unto Death,/ and I find it
  fitting for myself today. 

  The despair of possibility is the crippling feeling you get in front
  of a blank page. Or more broadly it is the feeling you get in the
  face of the blank rest of your life. There are a number of ways to
  try to resolve this despair. (I might be wrong about applying this
  category here.) We can devote ourselves to our own fulfillment or an
  ethical ideal. We can even devote ourselves to a religion in an act
  of faith. Kierkegaard spends a lot of time on these different
  categories, and it is easy to get caught up in trying to think of
  them as simply a system.

  That's fine in many cases, but today I am interested in looking at how
  each of Kierkegaard's ways of resolving the despair of possibility
  can be understood as not only responses to the life project, but
  also as responses to individual projects and tasks in our lives. How
  do the various responses to despair interact with the terror of the
  blank page?
  
  What would it mean to take these categories into particular bits of
  life? In many of our areas of life we face things like the despair
  of possibility. I suppose the way forward is to choose one of
  Kierkegaard's three options. We can choose to please ourselves with
  our work. And that provides some guidance. We can choose to try to
  make our work good in itself and for others. That maybe provides
  more guidance. Or we can do it for God. What this means I do not
  really know. It has to somehow include the other options, but what
  this means is tricky. I need more time to find out what this means.
  Maybe it involves doing things for others and for yourself, but all
  somehow as an offering. Both you and others perfectly served but
  neither for themselves all somehow pointing beyond. Also,
  Kierkegaard had this idea of faith being the holding of the infinite
  within the finite. There is somehow a realization of meaning within
  existence. Maybe that is part of it as well.

* Typical Experiences
  :PROPERTIES:
  :EXPORT_FILE_NAME: typical-experiences.md
  :EXPORT_DATE: <2019-07-16 Tue>
  :END:
   We have certain experiences that we see as typical to us. This is
   interesting. We can tell a lot about what we think of ourselves and
   our identities by what experiences we call typical. What is
   interesting about them is that the list of things that we do that
   we see as typical does not necessarily match up with what we
   actually do all the time. You see this kind of behavior in people
   who are particularly hard on themselves. Failure is typical and
   success is a freak accident. This is amusingly still believed even
   when in that person's life the number of successes way over
   balances the number of failures. 

   Typical experiences flow out of who we think we are. They are
   expressions and manifestations of our identity. They allow us to
   have an existence within the constant ebb and flow of our
   experiences. They keep us from seeing things like our digestion and
   sweating as core to who we are. I would not want to live without
   this function of my identity, but it can often deceive us. Our
   subjective experience of ourselves can become strongly skewed and
   this likely by the same mechanism that helps us filter the signal
   from the noise in our day to day experience. Somehow we can get
   confused about what is the signal in our experiences and what is
   the noise. This confusion comes from a core interpretive mistake
   about who we are. 

   I know of no quick fix for this, but it is a call to look at other
   voices in determining who we are and especially the meaning of
   events in our lives. We too often jump to conclusions based on a
   clear idea of who we think we are. Maybe a good way forward is to
   think about the experiences themselves as if they were a part of
   another person we did not know. What would we assume about this
   person's identity and how would that contrast with ours. 

   
* The Burden of Fascination
  :PROPERTIES:
  :EXPORT_DATE: <2019-07-20 Sat> 
  :EXPORT_FILE_NAME: burden-of-fascination.md
  :END:
  Something I have noticed about myself is that I am seeminly capable
  of great things when I am excited about them. This is likely not a
  unique thing, but what might be more specific to me is the the gulf
  between me when I am interested in something and when I am just
  normal. Work that could take 15mins when I am very interested in
  something at least seems to take more like 45mins when I am not. Add
  a layer of dread around the work and we can add more time probably. 

  I have noticed this intuitively for much of my life and it has made
  me kind of superstitious. I have developed several funny quirks to
  help me try to control my level of interest. One for instance is
  that if I have an idea, I am hesitant to tell it to other people
  until it is fully developed because I am afraid that I will lose the
  steam I might need to write it down. I will be engrossed in
  explaining it to another person and then feel like any writing I do
  later is a boring recap. This habit has made me a bit cagey about
  talking about ideas at times and also maybe a little overly
  performance focused as well. Because if performance is what is most
  crucial for recognition then I should save my thoughts for that. My
  fear has been that otherwise my ideas and interests will die on the
  vine half developed.

  Now I have a few other tricks to help with this as well. Another is
  to try to cultivate a mental image that is attractive for the act of
  doing some sort of work. If I can create a system of meaning for
  something that I am doing then I can have an easier time finding it
  interesting. This helps, but it makes me feel like a slave to my
  curiousity and other passions. I am not sure what to do to alleviate
  this difficulty as well. 

  I have experience with the just do it anyway approach and it does
  work. However, my experience of the quality of the work seems so
  much lower in those times. I say experience because the work I have
  done in those situations is often not too bad, but I do not feel
  that is connected to something important at the same time. I don't
  have peace about doing it. 

  When something is fascinating to me it is like all of the questions
  and answers line up and I feel that I have something real to share
  with others. When something does not feel this way it feel like a
  plodding forward that is ultimately futile. I can still do work, but
  it is truly a labor.

  Now I realize maybe what I should just do is be willing to accept
  both of these ways of working as part of life. What interests me
  though I guess is how I can be a bit less of a slave to fascination,
  and also where the fascination comes from and what kills it. This is
  even more interesting to me right now because I find myself having
  more interest in somethings than I have had for awhile. I wonder
  why?
  
