#+hugo_base_dir: ../
#+hugo_section: posts
#+options: author:nil
* A New Notebook
  :PROPERTIES:
  :EXPORT_FILE_NAME: title-post.md
  :EXPORT_DATE: <2019-07-12 Fri>
  :END:
  If you are like me you probably own more nice looking notebooks than
  you have finished writing in. Buying a notebook is mostly like
  buying a difficult but impressive book to read. When you buy it you
  are buying what it promises to be for you. It promises to make you
  well read, or in the case of the notebook, it promises that you will
  have ideas worth writing down.

  Starting a blog is like this. 
  
  This blog is part of a naive attempt to be more public with my ideas
  and to work harder at drawing myself out into the wider world. This
  is not my inclination so it will be difficult. The choice of the
  title comes from Kierkegaard's /Sickness Unto Death,/ and I find it
  fitting for myself today. 

  The despair of possibility is the crippling feeling you get in front
  of a blank page. Or more broadly it is the feeling you get in the
  face of the blank rest of your life. There are a number of ways to
  try to resolve this despair. (I might be wrong about applying this
  category here.) We can devote ourselves to our own fulfillment or an
  ethical ideal. We can even devote ourselves to a religion in an act
  of faith. Kierkegaard spends a lot of time on these different
  categories, and it is easy to get caught up in trying to think of
  them as simply a system.

  That's fine in many cases, but today I am interested in looking at how
  each of Kierkegaard's ways of resolving the despair of possibility
  can be understood as not only responses to the life project, but
  also as responses to individual projects and tasks in our lives. How
  do the various responses to despair interact with the terror of the
  blank page?
  
  What would it mean to take these categories into particular bits of
  life? In many of our areas of life we face things like the despair
  of possibility. I suppose the way forward is to choose one of
  Kierkegaard's three options. We can choose to please ourselves with
  our work. And that provides some guidance. We can choose to try to
  make our work good in itself and for others. That maybe provides
  more guidance. Or we can do it for God. What this means I do not
  really know. It has to somehow include the other options, but what
  this means is tricky. I need more time to find out what this means.
  Maybe it involves doing things for others and for yourself, but all
  somehow as an offering. Both you and others perfectly served but
  neither for themselves all somehow pointing beyond. Also,
  Kierkegaard had this idea of faith being the holding of the infinite
  within the finite. There is somehow a realization of meaning within
  existence. Maybe that is part of it as well.

* Typical Experiences
  :PROPERTIES:
  :EXPORT_FILE_NAME: typical-experiences.md
  :EXPORT_DATE: <2019-07-16 Tue>
  :END:
   We have certain experiences that we see as typical to us. This is
   interesting. We can tell a lot about what we think of ourselves and
   our identities by what experiences we call typical. What is
   interesting about them is that the list of things that we do that
   we see as typical does not necessarily match up with what we
   actually do all the time. You see this kind of behavior in people
   who are particularly hard on themselves. Failure is typical and
   success is a freak accident. This is amusingly still believed even
   when in that person's life the number of successes way over
   balances the number of failures. 

   Typical experiences flow out of who we think we are. They are
   expressions and manifestations of our identity. They allow us to
   have an existence within the constant ebb and flow of our
   experiences. They keep us from seeing things like our digestion and
   sweating as core to who we are. I would not want to live without
   this function of my identity, but it can often deceive us. Our
   subjective experience of ourselves can become strongly skewed and
   this likely by the same mechanism that helps us filter the signal
   from the noise in our day to day experience. Somehow we can get
   confused about what is the signal in our experiences and what is
   the noise. This confusion comes from a core interpretive mistake
   about who we are. 

   I know of no quick fix for this, but it is a call to look at other
   voices in determining who we are and especially the meaning of
   events in our lives. We too often jump to conclusions based on a
   clear idea of who we think we are. Maybe a good way forward is to
   think about the experiences themselves as if they were a part of
   another person we did not know. What would we assume about this
   person's identity and how would that contrast with ours. 

* The Burden of Fascination
  :PROPERTIES:
  :EXPORT_DATE: <2019-07-20 Sat> 
  :EXPORT_FILE_NAME: burden-of-fascination.md
  :END:
  Something I have noticed about myself is that I am seeminly capable
  of great things when I am excited about them. This is likely not a
  unique thing, but what might be more specific to me is the the gulf
  between me when I am interested in something and when I am just
  normal. Work that could take 15mins when I am very interested in
  something at least seems to take more like 45mins when I am not. Add
  a layer of dread around the work and we can add more time probably. 

  I have noticed this intuitively for much of my life and it has made
  me kind of superstitious. I have developed several funny quirks to
  help me try to control my level of interest. One for instance is
  that if I have an idea, I am hesitant to tell it to other people
  until it is fully developed because I am afraid that I will lose the
  steam I might need to write it down. I will be engrossed in
  explaining it to another person and then feel like any writing I do
  later is a boring recap. This habit has made me a bit cagey about
  talking about ideas at times and also maybe a little overly
  performance focused as well. Because if performance is what is most
  crucial for recognition then I should save my thoughts for that. My
  fear has been that otherwise my ideas and interests will die on the
  vine half developed.

  Now I have a few other tricks to help with this as well. Another is
  to try to cultivate a mental image that is attractive for the act of
  doing some sort of work. If I can create a system of meaning for
  something that I am doing then I can have an easier time finding it
  interesting. This helps, but it makes me feel like a slave to my
  curiousity and other passions. I am not sure what to do to alleviate
  this difficulty as well. 

  I have experience with the just do it anyway approach and it does
  work. However, my experience of the quality of the work seems so
  much lower in those times. I say experience because the work I have
  done in those situations is often not too bad, but I do not feel
  that is connected to something important at the same time. I don't
  have peace about doing it. 

  When something is fascinating to me it is like all of the questions
  and answers line up and I feel that I have something real to share
  with others. When something does not feel this way it feel like a
  plodding forward that is ultimately futile. I can still do work, but
  it is truly a labor.

  Now I realize maybe what I should just do is be willing to accept
  both of these ways of working as part of life. What interests me
  though I guess is how I can be a bit less of a slave to fascination,
  and also where the fascination comes from and what kills it. This is
  even more interesting to me right now because I find myself having
  more interest in somethings than I have had for awhile. I wonder
  why?
  
* The Need of Uninhibited Productivity
  :PROPERTIES:
  :EXPORT_DATE: <2019-07-23 Tue> 
  :EXPORT_FILE_NAME: the-need-of-uninhibited-productivity.md
  :END:
  I am not sure if I will publish this or not. It is something that
  has been on my mind lately and I am don't think I have finished
  thinking about it. I felt the need from the title several times in
  my life, but it was most intense I remember when I was working as a
  programmer. 

  I got a strong taste of it again the other day when I was looking at
  programming job postings. It brought back memories from when I was
  trying to get started in programming years ago. It is a particularly
  strange feeling. I will try to describe it.

  The way it starts is looking at various challenges and telling
  myself in a rushed sort of anxious way yeah I can do that. That is
  easy. Then I have coupled with it this dream of being able to do the
  job both brilliantly and competently. Even now I feel a pull to try
  to learn and be brilliant. There is a strong push to accomplish
  enough that I feel at peace. It is a frantic feeling, and I have
  found it keeping me from actually learning well. In my haste I tend
  to close my eyes to nuances and also panic at any little difficulty. 

  This really is one of the least wise frames of mind that I get into.
  I think it is rooted maybe a little deeper than I had thought
  before. In the past I thought that it had to do with old work
  struggles, but now I am wondering if it goes back to the way that I
  felt when I left L'Abri the first time. The feeling of both
  excitement and fear as I thought about my leaving behind grad school
  plans. I think that writing papers for school is possibly part of
  the archeology of this experience I have. I am not sure yet though.
  I find it pretty mystifying.
* Gifting and Belonging
  :PROPERTIES:
  :EXPORT_DATE: <2019-07-26 Fri> 
  :EXPORT_FILE_NAME: gifting-and-belonging.md
  :END:

  These posts are becoming increasingly personal lately, but I guess I
  am okay with that for now. The thing on my mind today is that in my
  life (and I think this is probably true for lots of people), I have
  felt a pressure to be amazing in certain things. The reason I think
  for this comes from a lot of places perfectionism being one of them,
  but what has come to mind today is new. It is in two parts. The
  first is that being amazing is a way of dodging anxiety of
  judgement, and the second is that an un-ending striving for evidence
  of competence can be a sign of an internal question about gifting
  and belonging.

  So we will start with the first one. There is a particular anxiety
  that I experience as it relates to performance. Afterwards, I wonder
  if people think I have done a bad job. This is probably related to
  how judgmental I have been of people in the past. So my solution to
  the anxiety is not to judge the quality of what I have done myself.
  I renounce that work in favor of being amazing. If I amaze enough
  people and get enough compliments then I can rest knowing that I
  don't have to worry about what people are thinking. I will know what
  they are thinking more or less and that then ends the anxiety. 

  This has some problems though. The main one being that it is
  impossible to always amaze people and that compliments are not
  always trustworthy. So it is not a real solution to the anxiety.
  However, there is another problem though that is worse. Being overly
  concerned with people's approval can at its worst result in not
  caring if what you are saying is true or not. This is very dangerous
  because under this motivaiton of pleasing others you can feel like a
  success whether or not you are teaching lies. That is a big problem.

  It would be better and more effective to come up with a way of
  deciding for myself if I have done well or not. Other people would
  be part of this, but shouldn't be a slave to people's reactions and
  often their immediate reactions.
  
  So now for the second part. I have discovered that with many things
  that I do I find myself trying to reach a level of expertise that
  will finally prove to myself that I belong in a certain role. This
  creates a frantic sense of constant preparation and never being good
  enough. Today though I have been thinking that actually it is not
  premature to acknowledge that I have certain gifts and belong in a
  certain role at least for the time being. I definitly can improve,
  but I don't think I should worry anymore about whether or not I
  should be doing what I am doing. 

  This is a pretty big revelation for me. And I am realizing more and
  more how many of the things I have done recently and possibly life
  plans I have had relate to the question of expertise as belonging. I
  think this is one of the reasons that I have been wondering about
  grad school. I want to belong in the world of ideas. Now I am
  feeling some what sheepishly that in fact I do belong in the world
  of ideas. Maybe I am more the guy that slovels poop in the world of
  ideas than its king, but I think that I can at least say I belong. I
  wonder how easy it will be to keep hold of this understanding of my
  place.
  
  I think that there is likely an interesting conversation to have on
  this idea of expertise and belonging as it relates to identity. I
  would like to think about this more. We often talk about finding our
  identity with God and Christ. However, this language does not always
  leave room in the world of action and expertise. Identity is just as
  at work there though.

* Symbolics of the present age
  :PROPERTIES:
  :EXPORT_DATE: <2019-08-15 Thu>
  :EXPORT_FILE_NAME: symbolics-of-the-present-age.md
  :END:

  So what I want explore a little today is deeply indebted to Philip
  Rieff's ideas about culture. He saw a culture as the system of links
  between a group of people that allow for trust and cooperation while
  also a release from deep conformity. This functions because each
  culture contains a symbolic system of control and a symbolic system
  of remission or release.

  The notion of symbolic is important because the ways that these two
  systems work is not through some deeply propositional argument, but
  instead through deeply internalized cultural images and ideas. For
  instance in our present culture we have the idea of the person that
  abandons their oppressive environment in search of their dreams.
  This particular version of the hero's journey is very powerful
  though perhaps a bit of a cliche.

  This particular example would also be of interest to Rieff in that
  it is unclear if it is from the symbolic of release or control. Does
  it imply a mandate or a release. It is this sort of equivocity that
  he would say is a sign of an impending cultural revolution.
  
  What I would like to look at today is certain cultural images that
  I have noticed in myself, that I have an inkling that might serve a
  strong contemporary cultural force. These what I call "the doormat"
  and the "dead end job". These are two powerful symbols that I think
  serve to amplify our expressivist individualist culture. 

  I want to be clear though, that while I call these things symbols I
  in no way want to claim that they are not real. What I do want to
  claim is that these preexisting phenomena of the doormat and dead end
  job are now elevated to a special status. This special status is
  that of cautionary tale and perhaps a mirror image of the good life.

  So to begin I would like to look at the doormat. The doormat is that
  person that has lost themselves in service of others. This is often
  portrayed in media in its most extreme from the female victim of
  domestic violence. Now I would not say that all portrayals of
  victims of domestic violence are motivated by expressive
  individualism, not at all. However, I would say that these
  expressions within media have in some cases been co-opted by a
  cultural impulse. This impulse is that the idea of a life lived for
  others is to be regarded with suspicion. 

  I have experienced this suspicion both internally and externally. I
  am a firm believer in the importance of a life of service, but
  always around every corner I find myself required to explain how the
  kind of service I think is important is not letting yourself be
  walked all over. This concern is right at the forefront of peoples
  minds. The result of this is not that rightly understood service in
  impossible in our cultural climate. It is instead that service takes
  more advocacy and as a result is often less valued. This in an
  indirect way contributes to more individualistic conceptions of
  flourishing. 
  
  The symbol of the dead end job has a similar function of
  individualizing people. However, instead of being focused on the
  social sphere it is operative in the sphere of work. Here we have
  the symbol of a person trapped in a job that offers them very little
  and from which they have to have the courage to liberate themselves.
  This is a real thing. However, where it ascends to the realm of the
  symbolic is in the way in which it serves as reinforcement of the
  narrative that where you will find fulfillment is not in an improved
  version of your current context but somewhere "out there". This is
  significant because the dead-end job serves to interpret many other
  situations that can be seen as analogous. People for instance not
  planning to work jobs for very long. There is this kind of transfer
  of the worst-case scenario to the general experience. All of this
  serves to intensify the current culture of individualism.
* New Schedules, Intuition and an Analysis of Lived Metaphor
  :PROPERTIES:
  :EXPORT_DATE: <2019-09-17 Tue>
  :EXPORT_FILE_NAME: new-schedules.md
  :END:
  I am not sure if it is something about my personality, but I often
  find myself very disrupted by changes in schedule. I have recently
  had a major change in schedule and I am not quite sure what I think
  about it.  Somethings things feel a little too free. When we can do
  anything we often don't no where to start and I feel a bit that way
  today. Classic despair of possibility. I even has on of Kierkegaard's
  books sitting on my desk right now. Maybe I will read it or
  something.

  A further difficulty of days like today is that today is a day off.
  I have already created a work schedule for myself. If it were a
  workday then I would not have to worry about it as much. However,
  there is usually an intuitive element to what I do on days off for
  me, and I think that intuition is a bit stunted by changes in
  schedule. Intuition is likely based at least in part on past
  experiences and that goes out the window when we face change. So if
  you are someone who uses intuition a lot either in your rest time or
  your work time then you are likely to have some issues when your
  schedule changes.
  
  I have to admit that even when it comes to planned daily work I tend
  to be a very intuitive person. I tend to want to do what feels
  right. The reason for this is that often my performance at least
  seems to be much better when I am flowing in the stream of
  intuition. It can be hard to push through in a productive way
  without it. 

  However, I have noticed that this might in part be objectively
  untrue. It feels true but I have at least on some occasions noticed
  that my work is still at least decent when I am just slogging
  through it. So I am not sure ultimately about this yet. 
  
  Another possibility is that confidence is part of the experience of
  intuition and the desire to do well and the uncertainty that comes
  with most work combine with a new schedule to create enough
  instability to make it impossible to continue forward in certain
  work. This can be particularly bad when the pressure is on.

  What seems to mitigate this in these situations is the creation of
  some sort of mental model of the new schedule. Perhaps drawing some
  on the ideas of /Metaphors We Live By/ (Lakoff & Johnson 1981) we
  establish an set metaphors that have come to structure the aspects
  of our different kinds of days. These metaphors then can be extended
  and it is their extension that creates intuitions about behaviors
  and plans.

  Then perhaps the solution is to consider what metaphors have been
  lost in the change of schedule and to think some about what has
  replaced them. As I think of this I have a feeling that I often have
  about the ideas in /Metaphors We Live By/ and that is that while I am
  sure that there are previous structuring experiences I do wonder how
  easily they can be turned into metaphors. But let's give it a go.

  So my typical day off starts out with two warring desires. The first
  is an hedonic desire to do whatever, it is that I want to do, and
  the second is a desire to go something good and admirable. These
  often present themselves as a desire for the same thing because I
  find working on some sort of impressive project very enjoyable at
  first. The war starts later when things get difficult. Then
  afterwards I lament the amount of time that has been used up in the
  day, and how little has been accomplished and how I feel betrayed by
  my projects and how little they have satisfied my desire to do
  something that I am proud of. 

  Then there is a low period.

  Then towards dinner I often pull out of this and then mostly enjoy
  the evening with my wife. 

  Okay so are there any metaphors in here?

  I suppose I have a misleading metaphor of day-off as empty platform.
  It is totally free from constraints. And this I guess then meshes
  with my typical metaphor for why I can't accomplish what I want. I
  am constrained by time and exhaustion. So the day off is a day of
  freedom from constraint and freedom to do. 

  However, there are still some constraints. The metaphor of day off
  as free playing field hide time constraints and also constraints of
  ability. These two things are often what is behind frustrations on
  other days as well. 

  And I experience frustration regularly because there are some lies
  backed into my metaphors and the way they are form and are shaped by
  my desires.
  
  So how does this fit in with the absence of the old schedule. I
  suppose part of it is that sense my schedule has changed I don't
  feel the same sorts of desire for the removal of constraints. I am
  not worn out and needing rest. At least, not in the normal way.
  Also, I am a bit discontent with the way I have been doing days off
  lately: a tendency towards escapism that I don't like.

  Anyway I can see that there is a lack of intuition because part of
  the content of typical metaphor of release of constraint is no
  longer entirely accurate to my felt experience. So, what then to do?
  How can I look at today not as a removal of constraint, but
  something else. What else is there? Opportunity for trying new and
  old things? This still has the notion of freedom that is a big part
  of day's off, but at the same time it does not rely in constraints.

  I am not sure if thinking this way will help anything, but I do find
  it interesting.

  



  
